In [2]:
import numpy as np
print(np.__version__)

1.26.4


### Level 1: Basic Attribute Handling
Project 1: Array Analyzer

Goal: Practice shape, ndim, dtype, itemsize, size, and .data.

Tasks:

    Create an array using np.arange(15).reshape(3,5).

    Write a function analyze_array(arr) that: Prints array

    Prints all attributes (shape, ndim, dtype, itemsize, size, type, data).

    Try with arrays of type int, float, and complex.

In [8]:
def analyze_array(arr):
    print(arr)
    print(f'dim: {arr.ndim}')
    print(f'shape: {arr.shape}')
    print(f'dtype: {arr.dtype}')
    print(f'itemsize: {arr.itemsize}')
    print(f'size: {arr.size}')
    print(f'type: {type(arr)}')
    print(f'data (buffer address): {arr.data}')
    
    return arr, arr.ndim, arr.shape, arr.dtype, arr.itemsize, arr.size, type(arr), arr.data

int_arr = np.arange(start=1, stop=16, dtype=np.int64).reshape((3,5))
float_arr = np.arange(1, 16, dtype=np.float64).reshape((3,5))
comp_arr = np.arange(1,16, dtype=np.complex64).reshape((3,5))

In [11]:
int_res = analyze_array(int_arr)
print("=="*30)
float_res = analyze_array(float_arr)
print("=="*30)
comp_res = analyze_array(comp_arr)
print("=="*30)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
dim: 2
shape: (3, 5)
dtype: int64
itemsize: 8
size: 15
type: <class 'numpy.ndarray'>
data (buffer address): <memory at 0x000001EDED8D39F0>
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
dim: 2
shape: (3, 5)
dtype: float64
itemsize: 8
size: 15
type: <class 'numpy.ndarray'>
data (buffer address): <memory at 0x000001EDED8D2E90>
[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]
 [ 6.+0.j  7.+0.j  8.+0.j  9.+0.j 10.+0.j]
 [11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]]
dim: 2
shape: (3, 5)
dtype: complex64
itemsize: 8
size: 15
type: <class 'numpy.ndarray'>
data (buffer address): <memory at 0x000001EDED8D1220>


### Level 2: Array Creation & Reshaping
Project 2: Custom Matrix Creator

Goal: Practice array creation (array, zeros, ones, empty, arange, linspace) and reshape.

Tasks:

Create a menu system:

    Press 1 → Create from list/tuple.

    Press 2 → Zeros array.

    Press 3 → Ones array.

    Press 4 → Empty array.

    Press 5 → Arange array.

    Press 6 → Linspace array.

    After creating, ask the user if they want to reshape it (reshape(rows, cols)).

    Print final array in a clean format.

In [14]:
import numpy as np

def custom_matrix_creator():
    print("""
Press 1 → Create from list/tuple.
Press 2 → Zeros array.
Press 3 → Ones array.
Press 4 → Empty array.
Press 5 → Arange array.
Press 6 → Linspace array.
""")
    arr_no = int(input("Enter your choice (1-6): "))

    if arr_no == 1:
        arr_list_tup = input("Enter comma-separated numbers: ").split(',')
        arr = np.array([int(x) for x in arr_list_tup])
    elif arr_no == 2:
        shape = tuple(map(int, input("Enter shape (e.g. 3,4): ").split(',')))
        arr = np.zeros(shape)
    elif arr_no == 3:
        shape = tuple(map(int, input("Enter shape (e.g. 3,4): ").split(',')))
        arr = np.ones(shape)
    elif arr_no == 4:
        shape = tuple(map(int, input("Enter shape (e.g. 3,4): ").split(',')))
        arr = np.empty(shape)
    elif arr_no == 5:
        start = float(input("Enter start: "))
        stop = float(input("Enter stop: "))
        step = float(input("Enter step: "))
        arr = np.arange(start, stop, step)
    elif arr_no == 6:
        start = float(input("Enter start: "))
        stop = float(input("Enter stop: "))
        num = int(input("Enter number of samples: "))
        arr = np.linspace(start, stop, num)
    else:
        print("Invalid choice.")
        return

    reshape_opt = input("Do you want to reshape? (y/n): ").lower()
    if reshape_opt == 'y':
        rows = int(input("Enter number of rows: "))
        cols = int(input("Enter number of columns: "))
        try:
            arr = arr.reshape((rows, cols))
        except Exception as e:
            print(f"Reshape error: {e}")

    print("Final array:")
    print(arr)

custom_matrix_creator()


Press 1 → Create from list/tuple.
Press 2 → Zeros array.
Press 3 → Ones array.
Press 4 → Empty array.
Press 5 → Arange array.
Press 6 → Linspace array.

Final array:
[1 2 3]


### Level 3: Operations Playground
Project 3: Math Playground

Goal: Practice arithmetic, matrix multiplication, universal functions, and aggregation.

Tasks:

    Create two arrays A and B of size (3,3).

    Implement functions:

    elementwise_ops(A,B) → show A+B, A-B, A*B, A/B.

    matrix_ops(A,B) → show A@B and A.dot(B).

    universal_funcs(A) → apply np.sin, np.exp, np.sqrt.

    summary(A) → show sum, min, max, mean, std, cumsum.

    Print all results nicely.

In [ ]:
class Math_PlayGround:
    def __init__(self, A, B):
        self.A = A
        self.B = B

    def elementwise_ops(self):
        add = self.A + self.B
        sub = self.A - self.B
        mul = self.A * self.B
        div = self.A / self.B
        print(f'A+B= {add}')
        print(f'A-B= {sub}')
        print(f'A*B= {mul}')
        print(f'A/B= {div}')
        return add, sub, mul, div

    def matrix_ops(self):
        matmul = self.A @ self.B
        dotprod = self.A.dot(self.B)
        print(f"A@B (matrix multiplication)= {matmul}")
        print(f"AdotB (dot prod)= {dotprod}")
        return matmul, dotprod

    @staticmethod
    def universal_funcs(array):
        sin = np.sin(array)
        exp = np.exp(array)
        sqrt = np.sqrt(array)
        print(f'sin: {sin}')
        print(f'exp: {exp}')
        print(f'sqrt: {sqrt}')
        return sin, exp, sqrt

    @staticmethod
    def summary(array):
        total = np.sum(array)
        min_ = np.min(array)
        max_ = np.max(array)
        mean = np.mean(array)
        std = np.std(array)
        cumsum = np.cumsum(array)
        print(f"sum: {total}")
        print(f"min: {min_}")
        print(f"max: {max_}")
        print(f"mean: {mean}")
        print(f"std: {std}")
        print(f"cumsum: {cumsum}")
        return total, min_, max_, mean, std, cumsum

In [29]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

mpg = Math_PlayGround(A, B)

print("Elementwise Operations:")
add, sub, mul, div = mpg.elementwise_ops()
print()

print("Matrix Operations:")
matmul, dotprod = mpg.matrix_ops()
print()

print("Universal Functions on A:")
sin, exp, sqrt = Math_PlayGround.universal_funcs(A)
print()

print("Summary of A:")
total, min_, max_, mean, std, cumsum = Math_PlayGround.summary(A)

Elementwise Operations:
A+B= [[10 10 10]
 [10 10 10]
 [10 10 10]]
A-B= [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
A*B= [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
A/B= [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Matrix Operations:
A@B (matrix multiplication)= [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
AdotB (dot prod)= [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Universal Functions on A:
sin: [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
exp: [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
sqrt: [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Summary of A:
sum: 45
min: 1
max: 9
mean: 5.0
std: 2.581988897471611
cumsum: [ 1  3  6 10 15 21 28 36 45]


### 🔵 Level 4: Indexing & Slicing
Project 4: 3D Array Explorer

Goal: Practice slicing, ellipsis (...), iteration.

Tasks:

Create a 3D array using np.arange(24).reshape(2,3,4).

Implement:

get_slice(arr, row, col) → extract slices like arr[row, col].

get_last_row(arr) → use negative index.

use_ellipsis(arr) → demonstrate arr[..., 2].

reverse(arr) → reverse using [::-1].

Iterate through:

Each row in array.

Each element with .flat.

In [30]:
class ArrayExplorer:
    def __init__(self, arr):
        self.arr = arr

    def get_slice(self, row, col):
        return self.arr[row, col]

    def get_last_row(self):
        return self.arr[-1]

    def use_ellipsis(self):
        return self.arr[..., 2]

    def reverse(self):
        return self.arr[::-1]

    def iterate_rows(self):
        for i, row in enumerate(self.arr):
            print(f"Row {i}:")
            print(row)

    def iterate_elements(self):
        print("All elements:")
        for el in self.arr.flat:
            print(el, end=' ')
        print()

arr3d = np.arange(24).reshape(2, 3, 4)
explorer = ArrayExplorer(arr3d)

print("Original 3D array:")
print(arr3d)
print("\nget_slice(0, 1):")
print(explorer.get_slice(0, 1))
print("\nget_last_row():")
print(explorer.get_last_row())
print("\nuse_ellipsis():")
print(explorer.use_ellipsis())
print("\nreverse():")
print(explorer.reverse())
print("\nIterate rows:")
explorer.iterate_rows()
print("\nIterate elements:")
explorer.iterate_elements()

Original 3D array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

get_slice(0, 1):
[4 5 6 7]

get_last_row():
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

use_ellipsis():
[[ 2  6 10]
 [14 18 22]]

reverse():
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

Iterate rows:
Row 0:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row 1:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Iterate elements:
All elements:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
