# NumPy Complete Guide — Detailed Notebook

This notebook covers array creation, conversions, shape manipulation, stacking/splitting, indexing, ordering, operations, statistics, and basic linear algebra. Each section includes explanations and runnable examples.

In [2]:
import numpy as np
import os
from numpy import pi
rg = np.random.default_rng(0)
np.set_printoptions(precision=6, suppress=True)

## Array Creation

Functions covered: `arange`, `array`, `copy`, `empty`, `empty_like`, `eye`, `fromfile`, `fromfunction`, `identity`, `linspace`, `logspace`, `mgrid`, `ogrid`, `ones`, `ones_like`, `r_`, `zeros`, `zeros_like`.

Examples below:

In [6]:
# arange
a = np.arange(0, 10, 2)
print('arange:', a)

# array and copy
b = np.array([[1,2],[3,4]])
c = b.copy()
c[0,0] = 99
print('\noriginal b after c modified (b unchanged):\n', b, '\ncopy c:\n', c)

# empty / empty_like
e = np.empty((2,3))
print('\nempty(2,3):\n', e)

# zeros / ones and their _like variants
print('\nzeros:\n', np.zeros((2,3)))
print('\nones:\n', np.ones((2,3)))
print('\nzeros_like(b):\n', np.zeros_like(b))
print('\nones_like(b):\n', np.ones_like(b))

# eye / identity
print('\neye(4):\n', np.eye(4, k=1)) # 1 for upper diagonal, -1 for lower
print('\nidentity(3):\n', np.identity(3))

# linspace / logspace
print('\nlinspace 0..1 (5 pts):', np.linspace(0,1,5))
print('logspace 10^0 .. 10^3 (4 pts):', np.logspace(0,3,5))

# fromfunction
def f(i,j):
    return i + 10*j
print('\nfromfunction example (3x4):\n', np.fromfunction(f, (3,4), dtype=int))

# fromfile example using tofile/fromfile
tmp = np.arange(12, dtype=np.int32)
fn = 'tmp_binary.dat'
try:
    tmp.tofile(fn)
    read_back = np.fromfile(fn, dtype=np.int32)
    print('\nfromfile read back:', read_back)
finally:
    if os.path.exists(fn):
        os.remove(fn)

# mgrid / ogrid
x_dense, y_dense = np.mgrid[0:3, 0:4]
print('\nmgrid x_dense:\n', x_dense)
print('\nmgrid y_dense:\n', y_dense)
print('\nmgrid shapes:', x_dense.shape, y_dense.shape)

x_open, y_open = np.ogrid[0:3, 0:4]
print('\nogrid x_open:\n', x_open)
print('\nogrid y_open:\n', y_open)
print('ogrid shapes:', x_open.shape, y_open.shape)

# r_ concatenation helper
print('\nnp.r_[1:4, 0, 4] ->', np.r_[1:4, 0, 4])


arange: [0 2 4 6 8]

original b after c modified (b unchanged):
 [[1 2]
 [3 4]] 
copy c:
 [[99  2]
 [ 3  4]]

empty(2,3):
 [[0. 0. 0.]
 [0. 0. 0.]]

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

zeros_like(b):
 [[0 0]
 [0 0]]

ones_like(b):
 [[1 1]
 [1 1]]

eye(4):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

identity(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

linspace 0..1 (5 pts): [0.   0.25 0.5  0.75 1.  ]
logspace 10^0 .. 10^3 (4 pts): [   1.          5.623413   31.622777  177.827941 1000.      ]

fromfunction example (3x4):
 [[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]]

fromfile read back: [ 0  1  2  3  4  5  6  7  8  9 10 11]

mgrid x_dense:
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]

mgrid y_dense:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

mgrid shapes: (3, 4) (3, 4)

ogrid x_open:
 [[0]
 [1]
 [2]]

ogrid y_open:
 [[0 1 2 3]]
ogrid shapes: (3, 1) (1, 4)

np.r_[1:4, 0, 4] -> [1 2 3 0 4]


## Conversions

Functions: `ndarray.astype`, `atleast_1d`, `atleast_2d`, `atleast_3d`, `mat` (legacy).

In [7]:
a = np.array([1,2,3], dtype=np.int32)
print('original dtype:', a.dtype)
b = a.astype(np.float64)
print('after astype(float64):', b, b.dtype)

print('\natleast_1d(5) ->', np.atleast_1d(5))
print('atleast_2d([1,2,3]) ->\n', np.atleast_2d([1,2,3]))
print('atleast_3d([1,2,3]) ->\n', np.atleast_3d([1,2,3]))

m = np.mat([[1,2],[3,4]])
print('\nmat object:\n', m)


original dtype: int32
after astype(float64): [1. 2. 3.] float64

atleast_1d(5) -> [5]
atleast_2d([1,2,3]) ->
 [[1 2 3]]
atleast_3d([1,2,3]) ->
 [[[1]
  [2]
  [3]]]

mat object:
 [[1 2]
 [3 4]]


## Manipulations

Functions: `array_split`, `column_stack`, `concatenate`, `diagonal`, `dsplit`, `dstack`, `hsplit`, `hstack`, `ndarray.item`, `newaxis`, `ravel`, `repeat`, `reshape`, `resize`, `squeeze`, `swapaxes`, `take`, `transpose`, `vsplit`, `vstack`. Examples:

In [8]:
arr = np.arange(12).reshape(3,4)
print('arr:\n', arr)

print('\nreshape to (4,3):\n', arr.reshape(4,3))
print('\nravel ->', arr.ravel())
print('\ntranspose (T):\n', arr.T)

vec = np.array([4,2])
print('\nvec[:, newaxis]:\n', vec[:, np.newaxis])

print('\nrepeat(vec,2):', np.repeat(vec,2))

a3 = np.array([[[1],[2],[3]]])
print('\nshape before squeeze:', a3.shape)
print('after squeeze:', a3.squeeze().shape)

a4 = np.arange(24).reshape(2,3,4)
print('\nshape before swapaxes:', a4.shape)
print('after swapaxes(0,2):', np.swapaxes(a4,0,2).shape)

print('\narr.take([0, -1]):', arr.take([0, -1]))

b = np.arange(6)
print('\nb before resize:', b, 'shape', b.shape)
try:
    b.resize((3,2))
    print('b after resize:', b, 'shape', b.shape)
except Exception as ex:
    print('resize error:', ex)

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print('\nvstack:\n', np.vstack((A,B)))
print('\nhstack:\n', np.hstack((A,B)))
print('\ndstack shape:', np.dstack((A,B)).shape)
print('\ncolumn_stack with 1D arrays:\n', np.column_stack((np.array([1,2]), np.array([3,4]))))

arr2 = np.arange(12).reshape(2,6)
print('\narr2:\n', arr2)
print('\nhsplit into 3:\n', np.hsplit(arr2, 3))
print('\narray_split into 4 (may be uneven):\n', np.array_split(arr2, 4, axis=1))
print('\nvsplit into 2:\n', np.vsplit(arr2, 2))

print('\narr2.take([0,2], axis=1):\n', arr2.take([0,2], axis=1))


arr:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

ravel -> [ 0  1  2  3  4  5  6  7  8  9 10 11]

transpose (T):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

vec[:, newaxis]:
 [[4]
 [2]]

repeat(vec,2): [4 4 2 2]

shape before squeeze: (1, 3, 1)
after squeeze: (3,)

shape before swapaxes: (2, 3, 4)
after swapaxes(0,2): (4, 3, 2)

arr.take([0, -1]): [ 0 11]

b before resize: [0 1 2 3 4 5] shape (6,)
b after resize: [[0 1]
 [2 3]
 [4 5]] shape (3, 2)

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]

dstack shape: (2, 2, 2)

column_stack with 1D arrays:
 [[1 3]
 [2 4]]

arr2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

hsplit into 3:
 [array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]

array_split into 4 (may be uneven):
 [array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4],
       [10]]), array([[ 5],
       [11]])

## Logical Questions / Conditional Selection

Functions: `all`, `any`, `nonzero`, `where`.

In [ ]:
a = np.array([0,1,2,0])
print('all(a>0):', np.all(a>0))
print('any(a>0):', np.any(a>0))
print('\nnonzero(a):', np.nonzero(a))
print('where(a==0):', np.where(a==0))

x = np.arange(5)
print('\nwhere example (x if x>2 else -x):\n', np.where(x>2, x, -x))


## Ordering / Searching

Functions: `argmax`, `argmin`, `argsort`, `max`, `min`, `ptp`, `searchsorted`, `sort`.

In [ ]:
arr = np.array([3,1,4,1,5,9])
print('argmax:', arr.argmax(), 'value:', arr.max())
print('argmin:', arr.argmin(), 'value:', arr.min())
print('argsort:', arr.argsort())
print('ptp (max-min):', arr.ptp())

s = np.array([1,3,5,7])
print('\nsearchsorted for 4 ->', np.searchsorted(s,4))
print('searchsorted side=right for 5 ->', np.searchsorted(s,5, side="right"))
print('\nsorted copy:', np.sort(arr))


## Array Operations

Functions: `choose`, `compress`, `cumprod`, `cumsum`, `inner`, `ndarray.fill`, `imag`, `prod`, `put`, `putmask`, `real`, `sum`.

In [ ]:
print("choose example (simple):", np.choose([0,1,0,1], [100,200]))

a = np.arange(10)
print('\ncompress a%2==0:', np.compress(a%2==0, a))

b = np.array([1,2,3,4])
print('\ncumsum:', np.cumsum(b))
print('cumprod:', np.cumprod(b))

x = np.array([1,2,3])
y = np.array([4,5,6])
print('\ninner(x,y):', np.inner(x,y))
print('vdot(x,y):', np.vdot(x,y))

c = np.empty(4)
c.fill(7)
print('\nfilled:', c)

z = np.array([1+2j, 3+4j])
print('\nreal:', z.real, 'imag:', z.imag)

print('\nprod(b):', b.prod(), 'sum(b):', b.sum())

arr = np.arange(6)
np.put(arr, [0,3], [99,100])
print('\narr after put:', arr)
mask = np.array([True, False, True, False, True, False])
np.putmask(arr, mask, -1)
print('arr after putmask:', arr)


## Basic Statistics

Functions: `cov`, `mean`, `std`, `var`.

In [ ]:
data = np.array([1.0,2.0,3.0,4.0])
print('mean:', data.mean(), 'std:', data.std(), 'var:', data.var())

x = np.array([0,1,2,3])
y = np.array([3,4,5,6])
print('\ncovariance matrix of x and y:\n', np.cov(x,y))


## Basic Linear Algebra

Functions: `cross`, `dot`, `outer`, `linalg.svd`, `vdot`. Examples below.

In [ ]:
u = np.array([1,2,3])
v = np.array([4,5,6])
print('dot(u,v):', np.dot(u,v))
print('outer(u,v):\n', np.outer(u,v))
print('cross(u,v):', np.cross(u,v))

M = np.array([[1.,2.],[3.,4.],[5.,6.]])
U,s,VT = np.linalg.svd(M, full_matrices=False)
print('\nSVD shapes U,s,VT:', U.shape, s.shape, VT.shape)
print('singular values:', s)


----

### Notes
- Run cells sequentially to see outputs.
- Use `help(np.func)` in a live notebook to view parameters and docstrings.
----

Saved as `NumPy_Complete_Guide.ipynb`