In [2]:
import numpy as np

### Level 1: Shape Manipulation
Project 1: Array Shape Explorer

Goal: Explore reshape, ravel, resize, transpose, and -1.

Tasks:

    Generate a 3x4 array with random integers.

    Implement functions:

    flatten_array(arr) → returns arr.ravel().

    reshape_array(arr, rows, cols) → returns arr.reshape(rows, cols).

    transpose_array(arr) → returns arr.T.

    resize_inplace(arr, new_shape) → modifies array with .resize().

    auto_reshape(arr, rows, -1) → reshapes with -1.

    Compare .reshape() vs .resize() (show original array changes in one but not the other).

In [3]:
class ArrayShapeExplorer:
    def __init__(self, arr):
        self.arr = arr
    def flatten_array(self):
        return self.arr.ravel()
    def transpose_array(self):
        return self.arr.T
    def resize_inplace(self, new_shape:tuple):
        return self.arr.resize(new_shape)  # it will change the original array
    def auto_reshape(self, rows, columns=-1):
        return self.arr.reshape((rows, columns))
    def reshape(self, new_shape:tuple):
        return self.arr.reshape(new_shape)

In [4]:
arr = np.random.randint(0, 10, (3, 4))
explorer = ArrayShapeExplorer(arr)

print("Original array:")
print(arr)

print("\nFlattened array:")
print(explorer.flatten_array())

print("\nTransposed array:")
print(explorer.transpose_array())

print("\nReshape to (4, 3):")
print(explorer.reshape((4, 3)))


print("\nArray after auto_reshape to (4, -1):")
print(explorer.auto_reshape(4, -1)  )

explorer.resize_inplace((2, 6))
print("\nArray after resize_inplace to (2, 6):")
print(arr)



Original array:
[[1 6 7 1]
 [4 6 5 4]
 [0 5 2 6]]

Flattened array:
[1 6 7 1 4 6 5 4 0 5 2 6]

Transposed array:
[[1 4 0]
 [6 6 5]
 [7 5 2]
 [1 4 6]]

Reshape to (4, 3):
[[1 6 7]
 [1 4 6]
 [5 4 0]
 [5 2 6]]

Array after auto_reshape to (4, -1):
[[1 6 7]
 [1 4 6]
 [5 4 0]
 [5 2 6]]

Array after resize_inplace to (2, 6):
[[1 6 7 1 4 6]
 [5 4 0 5 2 6]]


### Level 2: Stacking Arrays
Project 2: Array Merger Tool

Goal: Practice stacking (vstack, hstack, column_stack, r_, c_).

    Tasks:

    Generate two random (2,2) arrays A and B.

    Create a function stack_arrays(A, B) that:

    Prints np.vstack((A,B))

    Prints np.hstack((A,B))

    Prints np.column_stack((A,B))

    Prints np.r_[A,B] and np.c_[A,B].

    Take two 1D arrays (like [4,2] and [3,8]) and show the difference between hstack, column_stack, and using [:, newaxis].

In [5]:
def stack_arrays(A, B):
    results = {
        "vstack": np.vstack((A, B)),
        "hstack": np.hstack((A, B)),
        "column_stack": np.column_stack((A, B)),
        "row_stack": np.row_stack((A, B)),
        "r_": np.r_[A, B],
        "c_": np.c_[A, B]
    }
    return results

A = np.random.randint(low=1, high=13, size=(4, 3))
B = np.random.randint(low=1, high=13, size=(4, 3))

results = stack_arrays(A, B)
print(f"A: {A}")
print(f"B: {B}")
for key, value in results.items():
    print(f"\n{key}:\n{value}")

A: [[ 3  5  3]
 [ 5 11  9]
 [ 2  6 12]
 [ 4  7  8]]
B: [[ 2 10  3]
 [ 1 12  6]
 [ 3  6  9]
 [ 7 10  2]]

vstack:
[[ 3  5  3]
 [ 5 11  9]
 [ 2  6 12]
 [ 4  7  8]
 [ 2 10  3]
 [ 1 12  6]
 [ 3  6  9]
 [ 7 10  2]]

hstack:
[[ 3  5  3  2 10  3]
 [ 5 11  9  1 12  6]
 [ 2  6 12  3  6  9]
 [ 4  7  8  7 10  2]]

column_stack:
[[ 3  5  3  2 10  3]
 [ 5 11  9  1 12  6]
 [ 2  6 12  3  6  9]
 [ 4  7  8  7 10  2]]

row_stack:
[[ 3  5  3]
 [ 5 11  9]
 [ 2  6 12]
 [ 4  7  8]
 [ 2 10  3]
 [ 1 12  6]
 [ 3  6  9]
 [ 7 10  2]]

r_:
[[ 3  5  3]
 [ 5 11  9]
 [ 2  6 12]
 [ 4  7  8]
 [ 2 10  3]
 [ 1 12  6]
 [ 3  6  9]
 [ 7 10  2]]

c_:
[[ 3  5  3  2 10  3]
 [ 5 11  9  1 12  6]
 [ 2  6 12  3  6  9]
 [ 4  7  8  7 10  2]]


In [6]:
def stack_arrays(A, B):
    print("np.vstack((A, B)):\n", np.vstack((A, B)))
    print("\nnp.hstack((A, B)):\n", np.hstack((A, B)))
    print("\nnp.column_stack((A, B)):\n", np.column_stack((A, B)))
    print("\nnp.r_[A, B]:\n", np.r_[A, B])
    print("\nnp.c_[A, B]:\n", np.c_[A, B])
    print("\nnp.concatenate:\n", np.concatenate((A,B), axis=1))

A = np.random.randint(1, 10, (2, 2))
B = np.random.randint(1, 10, (2, 2))
print("A:\n", A)
print("B:\n", B)
stack_arrays(A, B)

a1 = np.array([4, 2])
a2 = np.array([3, 8])
print("\n1D arrays:")
print("a1:", a1)
print("a2:", a2)
print("\nhstack:", np.hstack((a1, a2)))
print("column_stack:", np.column_stack((a1, a2)))
print("a1[:, np.newaxis]:\n", a1[:, np.newaxis])
print("a2[:, np.newaxis]:\n", a2[:, np.newaxis])
print("column_stack with newaxis:\n", np.column_stack((a1[:, np.newaxis], a2[:, np.newaxis])))

A:
 [[2 2]
 [1 6]]
B:
 [[3 4]
 [5 8]]
np.vstack((A, B)):
 [[2 2]
 [1 6]
 [3 4]
 [5 8]]

np.hstack((A, B)):
 [[2 2 3 4]
 [1 6 5 8]]

np.column_stack((A, B)):
 [[2 2 3 4]
 [1 6 5 8]]

np.r_[A, B]:
 [[2 2]
 [1 6]
 [3 4]
 [5 8]]

np.c_[A, B]:
 [[2 2 3 4]
 [1 6 5 8]]

np.concatenate:
 [[2 2 3 4]
 [1 6 5 8]]

1D arrays:
a1: [4 2]
a2: [3 8]

hstack: [4 2 3 8]
column_stack: [[4 3]
 [2 8]]
a1[:, np.newaxis]:
 [[4]
 [2]]
a2[:, np.newaxis]:
 [[3]
 [8]]
column_stack with newaxis:
 [[4 3]
 [2 8]]


### Level 3: Splitting Arrays
Project 3: Array Splitter Tool

Goal: Master hsplit, vsplit, array_split.

    Tasks:

    Generate a 2x12 random array.

    Write a function split_array(arr) that:

    Splits into 3 equal parts horizontally with hsplit.

    Splits after the 3rd and 4th column with hsplit(arr, (3,4)).

    Splits vertically into 2 halves with vsplit.

    Uses array_split(arr, 5, axis=1) to split into 5 uneven parts.

    Print all sub-arrays neatly.

In [7]:
def split_array(arr):
    print(arr)

arr = np.random.randint(0,100, (2,12))
np.hsplit(arr, 3)
np.hsplit(arr, (3, 4))
np.split(arr, 2)
np.array_split(arr, 5, axis=1)

[array([[14, 76, 27],
        [18, 58,  3]]),
 array([[35, 96, 62],
        [70, 54, 51]]),
 array([[41, 61],
        [30, 78]]),
 array([[69, 30],
        [82, 15]]),
 array([[46, 83],
        [96, 59]])]

In [8]:
def split_array(arr):
    print("Original array:\n", arr)

    hsplit_3 = np.hsplit(arr, 3)
    print("\nSplit into 3 equal parts (hsplit):", hsplit_3)
    print("=="*30)
    for i, part in enumerate(hsplit_3):
        print(f"Part {i+1}:\n{part}")

    hsplit_custom = np.hsplit(arr, (3, 4))
    print("\nSplit after 3rd and 4th column (hsplit(arr, (3,4))):", hsplit_custom)
    print("=="*30)
    for i, part in enumerate(hsplit_custom):
        print(f"Part {i+1}:\n{part}")

    vsplit_2 = np.vsplit(arr, 2)
    print("\nSplit vertically into 2 halves (vsplit):", vsplit_2)
    print("=="*30)
    for i, part in enumerate(vsplit_2):
        print(f"Part {i+1}:\n{part}")

    array_split_5 = np.array_split(arr, 5, axis=1)
    print("\nSplit into 5 uneven parts (array_split, axis=1):", array_split_5)
    print("=="*30)
    for i, part in enumerate(array_split_5):
        print(f"Part {i+1}:\n{part}")

arr = np.random.randint(0, 100, (2, 12))
split_array(arr)

Original array:
 [[94 11 38 37 73 76 98 13 30 77 71 20]
 [59 68 65 30 35 52 85 48  8 82  6 52]]

Split into 3 equal parts (hsplit): [array([[94, 11, 38, 37],
       [59, 68, 65, 30]]), array([[73, 76, 98, 13],
       [35, 52, 85, 48]]), array([[30, 77, 71, 20],
       [ 8, 82,  6, 52]])]
Part 1:
[[94 11 38 37]
 [59 68 65 30]]
Part 2:
[[73 76 98 13]
 [35 52 85 48]]
Part 3:
[[30 77 71 20]
 [ 8 82  6 52]]

Split after 3rd and 4th column (hsplit(arr, (3,4))): [array([[94, 11, 38],
       [59, 68, 65]]), array([[37],
       [30]]), array([[73, 76, 98, 13, 30, 77, 71, 20],
       [35, 52, 85, 48,  8, 82,  6, 52]])]
Part 1:
[[94 11 38]
 [59 68 65]]
Part 2:
[[37]
 [30]]
Part 3:
[[73 76 98 13 30 77 71 20]
 [35 52 85 48  8 82  6 52]]

Split vertically into 2 halves (vsplit): [array([[94, 11, 38, 37, 73, 76, 98, 13, 30, 77, 71, 20]]), array([[59, 68, 65, 30, 35, 52, 85, 48,  8, 82,  6, 52]])]
Part 1:
[[94 11 38 37 73 76 98 13 30 77 71 20]]
Part 2:
[[59 68 65 30 35 52 85 48  8 82  6 52]]

Split in

### Level 4: Combined Shape & Stack Playground
Project 4: Matrix Builder & Breaker

Goal: Combine reshaping + stacking + splitting.

    Tasks:

    Start with np.arange(1, 13) and reshape it into (3,4).

    Reshape it into (2,6) and (4,3).

    Stack it with a new (3,4) random array using both vstack and hstack.

    Split it back into chunks (hsplit into 2, vsplit into 3).

    Flatten it (ravel) and rebuild it (reshape(-1,2)).

In [9]:
arr = np.arange(1,13)
print(f'aramge: {arr}')
arr = arr.reshape((3,4))
print(f'reshape 3,4: {arr}')
arr = arr.reshape((4,3))
print(f'reshape 4,3: {arr}')
stack = np.arange(1,13).reshape((4,3))
print(f'stack: {stack}')
new_arr = np.hstack((arr, stack))
print(f'new arr hstack: {new_arr}')
new_arr = np.vstack((arr, stack))
print(f'new arr vstack: {new_arr}')
arr = arr.ravel()
print(f'ravle: {arr}')
arr = arr.reshape((-1,2))
print(f'rebuild: {arr}')

aramge: [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape 3,4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape 4,3: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
stack: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
new arr hstack: [[ 1  2  3  1  2  3]
 [ 4  5  6  4  5  6]
 [ 7  8  9  7  8  9]
 [10 11 12 10 11 12]]
new arr vstack: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ravle: [ 1  2  3  4  5  6  7  8  9 10 11 12]
rebuild: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [10]:
arr = np.arange(1, 13)
print("Original 1D array:\n", arr)

arr_3x4 = arr.reshape((3, 4))
print("\nReshaped to (3, 4):\n", arr_3x4)

arr_2x6 = arr.reshape((2, 6))
print("\nReshaped to (2, 6):\n", arr_2x6)

arr_4x3 = arr.reshape((4, 3))
print("\nReshaped to (4, 3):\n", arr_4x3)

rand_3x4 = np.random.randint(0, 100, (3, 4))
print("\nRandom (3, 4) array:\n", rand_3x4)

hstacked = np.hstack((arr_3x4, rand_3x4))
print("\nHstacked (3, 8):\n", hstacked)

vstacked = np.vstack((arr_3x4, rand_3x4))
print("\nVstacked (6, 4):\n", vstacked)

hsplit_2 = np.hsplit(arr_3x4, 2)
print("\nHsplit into 2 parts:")
for i, part in enumerate(hsplit_2):
    print(f"Part {i+1}:\n{part}")

vsplit_3 = np.vsplit(arr_3x4, 3)
print("\nVsplit into 3 parts:")
for i, part in enumerate(vsplit_3):
    print(f"Part {i+1}:\n{part}")

flattened = arr_3x4.ravel()
print("\nFlattened array:\n", flattened)

rebuilt = flattened.reshape(-1, 2)
print("\nRebuilt to (-1, 2):\n", rebuilt)

Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to (2, 6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped to (4, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Random (3, 4) array:
 [[41 50 15 66]
 [42 23 81 44]
 [83 16 27 90]]

Hstacked (3, 8):
 [[ 1  2  3  4 41 50 15 66]
 [ 5  6  7  8 42 23 81 44]
 [ 9 10 11 12 83 16 27 90]]

Vstacked (6, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [41 50 15 66]
 [42 23 81 44]
 [83 16 27 90]]

Hsplit into 2 parts:
Part 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Part 2:
[[ 3  4]
 [ 7  8]
 [11 12]]

Vsplit into 3 parts:
Part 1:
[[1 2 3 4]]
Part 2:
[[5 6 7 8]]
Part 3:
[[ 9 10 11 12]]

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Rebuilt to (-1, 2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### Level 5: Shape Manipulation Challenge Project
Project 5: NumPy Data Processor

Goal: Realistic-style mini project simulating data reshaping and preparation.

Scenario:
You are preprocessing sensor data. Each sensor outputs 12 readings per second, and you log data from 2 sensors for 10 seconds.

Tasks:

    Create a 2x120 array (2 sensors, 120 readings each).

    Reshape it into (20,12) blocks for easier analysis.

    Split the data into:

    First 60 readings

    Last 60 readings

    Each split further divided into 3 equal chunks.

    Stack the chunks back into a single combined array (vstack + hstack).

    Flatten the entire processed data and reshape into a single column vector (reshape(-1,1)).

In [11]:
# Create a 2x120 array (2 sensors, 120 readings each).
sensor_arr_2x120 = np.random.randint(1,1001, size=(2,120))
# print(f'sensor array 2x120: {sensor_arr_2x120}')

# Reshape it into (20,12) blocks for easier analysis.
sensor_arr_20x12 = sensor_arr_2x120.reshape((20,12))
# print(f'sensor array 20x12: {sensor_arr_20x12}')

# Split the data into: First 60 readings, Last 60 readings
first_60, second_60 =np.vsplit(sensor_arr_20x12, 2)

# Each split further divided into 3 equal chunks.
first_60_first_chunk, first_60_seccond_chunk, first_60_third_chunk = np.array_split(first_60, 3, axis=1)
second_60_first_chunk, second_60_seccond_chunk, second_60_third_chunk = np.array_split(second_60, 3, axis=1)

# Stack the chunks back into a single combined array (vstack + hstack).
first_60_modified = np.vstack((first_60_first_chunk, first_60_seccond_chunk, first_60_third_chunk)) 
second_60_modified = np.vstack((second_60_first_chunk, second_60_seccond_chunk, second_60_third_chunk))
sensor_arr_20x12_modified = np.hstack((first_60_modified, second_60_modified))

# Flatten the entire processed data and reshape into a single column vector (reshape(-1,1)).
flat_arr = sensor_arr_20x12_modified.ravel()
column_vector = flat_arr.reshape((-1,1))

print(column_vector)

[[ 364]
 [ 674]
 [ 135]
 [ 507]
 [  39]
 [ 453]
 [ 354]
 [ 921]
 [ 731]
 [ 601]
 [ 809]
 [ 791]
 [ 845]
 [  19]
 [ 206]
 [  50]
 [ 317]
 [ 316]
 [ 400]
 [ 256]
 [ 844]
 [ 519]
 [ 259]
 [ 733]
 [ 907]
 [ 975]
 [ 391]
 [ 406]
 [ 814]
 [ 723]
 [ 602]
 [ 850]
 [ 141]
 [ 809]
 [ 509]
 [   8]
 [ 637]
 [ 954]
 [ 716]
 [ 775]
 [ 523]
 [ 150]
 [ 535]
 [ 857]
 [ 695]
 [ 675]
 [  10]
 [  50]
 [ 172]
 [ 515]
 [ 212]
 [ 431]
 [ 698]
 [ 627]
 [ 222]
 [ 443]
 [ 438]
 [ 399]
 [ 931]
 [ 255]
 [ 715]
 [  50]
 [ 541]
 [ 349]
 [ 724]
 [  94]
 [ 932]
 [ 427]
 [ 527]
 [  83]
 [ 407]
 [  60]
 [ 501]
 [ 940]
 [ 871]
 [ 828]
 [ 318]
 [ 301]
 [  12]
 [ 298]
 [ 346]
 [ 911]
 [1000]
 [ 173]
 [ 186]
 [ 797]
 [ 602]
 [ 126]
 [ 150]
 [ 252]
 [ 968]
 [ 518]
 [ 896]
 [ 329]
 [ 540]
 [ 184]
 [ 667]
 [ 432]
 [ 235]
 [ 645]
 [ 910]
 [ 816]
 [  23]
 [ 866]
 [ 302]
 [ 293]
 [ 678]
 [ 485]
 [ 220]
 [ 645]
 [ 423]
 [ 674]
 [ 828]
 [ 976]
 [ 243]
 [ 211]
 [  58]
 [ 576]
 [ 493]
 [ 789]
 [  92]
 [  32]
 [ 297]
 [ 265]
 [ 477]


In [45]:
# Create a 2x120 array (2 sensors, 120 readings each).
sensor_arr_2x120 = np.random.randint(1, 1001, size=(2, 120))
print("sensor_arr_2x120:\n", sensor_arr_2x120)

# Reshape it into (20,12) blocks for easier analysis.
sensor_arr_20x12 = sensor_arr_2x120.reshape((20, 12))
print("\nsensor_arr_20x12:\n", sensor_arr_20x12)

# Split the data into: First 60 readings, Last 60 readings
first_60, second_60 = np.vsplit(sensor_arr_20x12, 2)
print("\nFirst 60 readings (first_60):\n", first_60)
print("\nLast 60 readings (second_60):\n", second_60)

# Each split further divided into 3 equal chunks.
first_60_first_chunk, first_60_seccond_chunk, first_60_third_chunk = np.array_split(first_60, 3, axis=1)
second_60_first_chunk, second_60_seccond_chunk, second_60_third_chunk = np.array_split(second_60, 3, axis=1)
print("\nfirst_60_first_chunk:\n", first_60_first_chunk)
print("\nfirst_60_seccond_chunk:\n", first_60_seccond_chunk)
print("\nfirst_60_third_chunk:\n", first_60_third_chunk)
print("\nsecond_60_first_chunk:\n", second_60_first_chunk)
print("\nsecond_60_seccond_chunk:\n", second_60_seccond_chunk)
print("\nsecond_60_third_chunk:\n", second_60_third_chunk)

# Stack the chunks back into a single combined array (vstack + hstack).
first_60_modified = np.vstack((first_60_first_chunk, first_60_seccond_chunk, first_60_third_chunk)) 
second_60_modified = np.vstack((second_60_first_chunk, second_60_seccond_chunk, second_60_third_chunk))
print("\nfirst_60_modified (stacked chunks):\n", first_60_modified)
print("\nsecond_60_modified (stacked chunks):\n", second_60_modified)

sensor_arr_20x12_modified = np.hstack((first_60_modified, second_60_modified))
print("\nsensor_arr_20x12_modified (final combined):\n", sensor_arr_20x12_modified)

# Flatten the entire processed data and reshape into a single column vector (reshape(-1,1)).
flat_arr = sensor_arr_20x12_modified.ravel()
print("\nFlattened array:\n", flat_arr)

column_vector = flat_arr.reshape((-1, 1))
print("\nColumn vector:\n", column_vector)

sensor_arr_2x120:
 [[606 297 359 537 549 123 691 503 749 343 177 548  82 284 889 320 215 997
  136 473 421 473 937 782 978 443 226 190 412 586 408  46 677 620 737 548
  701 174 667 567 416 543 936 533  86 524 578 754 585  67 535 345 978 256
  409 219 684 148 626 926 966 461  89 410 772 900 646 340 609 154 746 387
  590 947 912 480 429 602 250 400 574 792 569 623 195 589 898 693 129 152
  784  41 909 730 353 640 240 966 102 306 825 999 909 595 269 693  23 456
  469 725  77  48 296 487 898 355  38 783 146  57]
 [919 480 243 795 352 186   4 719 194 803 891 686 452 336 736 742  60 290
  410 812 139 353 951 271 473 741 234 830 838 930 967 829 395 300 549 596
  550 294  60 986 608 299 710 547 911 680 700  51 935 621 620 446 740 928
  127 587 439 480 106 259 823   3  98  24 803 622 400 517 718  84 166 204
  406 957 925 827  22 707 568 212 191 835 526 541 385 331 115 953  94 757
  714  76 623 226 566  92 207 526  31 653 985 964 803 429 499 178 848 966
  724 714 595 378 756 213 212 303 340 955 